### ISSUE TITLE
4.042 is not backwards compatible

### ISSUE THREAD

**Issue by mgruner** [perl5-dbi/DBD-mysql#106]
Hello @mbeijen! Our travis test tell me that the latest DBD::mysql breaks OTRS. We use `SET NAMES utf8;`, but not `mysql_enable_utf8 = 1` so far. This worked well in the past, but now with 4.042 everything breaks (see https://travis-ci.org/OTRS/otrs/jobs/209300597, for example).

Is that intended?

**Comment by mbeijen** [comment]
Well of course not!

This release fixed quite a few longstanding Unicode related issues.

So it might be we fixed a bug on which OTRS was depending, or it might be
we actually introduced a new error.

Would you be able to condense down a minimal example of an issue?

Too bad you did not catch this before the stable release. If you would use
'cpanm --dev' or the like in your .travis file you would have installed the
revel versions and we could detect the breakage more early on.

Cc: @pali
--
Michiel

Op do 9 mrt. 2017 om 13:28 schreef Martin Gruner <notifications@github.com>

**Comment by pali** [comment]
Hi! Please look at updated and hopefully correct documentation for `mysql_enable_utf8`: https://metacpan.org/pod/DBD::mysql#mysql_enable_utf8

In your logs are couple of warnings:
```
[Thu Mar  9 10:43:35 2017] otrs.Console.pl: Wide character in field 2 but mysql_enable_utf8 not set at /home/travis/build/OTRS/otrs/Kernel/System/DB.pm line 457.
```
Which means that you are passing wide (Unicode) perl scalar to DBD::mysql without enabling `mysql_enable_utf8`. Such thing was and still is wrong usage. `SET NAMES utf8;` just specify encoding for MySQL protocol and has nothing with perl Unicode.

To correctly pass perl Unicode scalar to MySQL you have 2 options:
* use `mysql_enable_utf8` and DBD::mysql will accept and returns perl wide (Unicode) scalars. Plus it will issue `SET NAMES utf8;` for you
* convert perl wide (Unicode) scalars to its UTF-8 representation yourself, set MySQL protocol to UTF-8 yourself and pass UTF-8 bytes to DBD::mysql. E.g. `$dbh->do(Encode::encode('UTF-8', 'SELECT * FROM t WHERE name = "\N{U+1000}"'))` Retrieved data then must be properly decoded to Unicode by: `my $str = $dbh->fetch... ; $str = Encode::decode('UTF-8', $str)`

**Comment by mgruner** [comment]
This is what we do until now:
- connect to unicode mysql db (without explicitly setting `mysql_enable_utf8`)
- send `SET NAMES utf8;`
- send unicode data

This worked until before 4.042, now it breaks. I'm pretty sure that OTRS would not be the only software affected by this change of behaviour. I haven't tried enabling `mysql_enable_utf8` yet as the documentation says that before 4.042 it was buggy. Should I only set the flag if the version of DBD::mysql is 4.042 or higher?

Thanks a lot for considering this!

**Comment by pali** [comment]
Can you provide code which send/receive those Unicode data? And what do you expect as return value? As first thing we need to what is the problem.

**Comment by mgruner** [comment]
Effectively, we call `DBD::mysql::db do()` with a statement like `INSERT INTO test_d (name_a, name_b) VALUES ( ?, ? )` and bind parameters containing the unicode data with utf8 flag enabled.

This leads to an error like:
```
otrs.Console.pl: DBD::mysql::db do failed: Incorrect string value: '\xF6' for column 'name_b' at row 1 at /ws/otrs5/Kernel/System/DB.pm line 461.
ERROR: OTRS-otrs.UnitTest-13 Perl: 5.18.2 OS: darwin Time: Thu Mar  9 14:13:17 2017

 Message: Incorrect string value: '\xF6' for column 'name_b' at row 1, SQL: 'INSERT INTO test_d (name_a, name_b) VALUES ( ?, ? )'
```

**Comment by pali** [comment]
> bind parameters containing the unicode data

Then error is expected. Passing wide (unicode) data to DBD::mysql was totally broken.

What do you expect that DBD::mysql should do with parameters which are wide strings? This is I think important to solve first.

**Comment by mgruner** [comment]
I'm not trying to argue that this is buggy. It's just that there might be more applications like OTRS depending on the previous behaviour.

**Comment by pali** [comment]
I know... but depending on incorrect, broken or unspecified behaviour is something which module cannot solve. Unspecified is even worse as nobody knows what is expected. Therefore I asked you above question so we could discuss if we can do something with "unspecified" to have it at least "specified". This may or may not help your or other modules... But if you have better idea, come up with it.

From your description it can be seen that your usage is wrong. And I think you have only two options:
1) Use your buggy code with older buggy DBD::mysql version when combination of both seems working fine
2) Fix your code so it would not be buggy anymore

If you want to achieve compatibility of your code to new and older DBD::mysql version you need to use only code/interface/parts which are not buggy. Which means passing binary octets to DBD::mysql instead of wide (unicode) strings and without mysql_enable_utf8. In my first post I wrote example with `Encode` module for proper encoding/decoding wide (unicode) strings to/from UTF-8.

**Comment by mgruner** [comment]
Thanks for the advice. I solved this now in our code by activating `mysql_enable_utf8` if DBD::mysql is 4.042 or newer.

**Comment by mgruner** [comment]
I changed our implementation to not use `mysql_enable_utf8` beause of #107.

**Comment by pali** [comment]
If you are need to deal with different encodings and different representations of data, then you either fully turn off `mysql_enable_utf8` and do (correct) encoding/decoding on your own. Or enable `mysql_enable_utf8` and pass correct types via `bind()` so DBI and DBD::mysql would know how to interpret them.

**Comment by pali** [comment]
See documentation update in https://github.com/perl5-dbi/DBD-mysql/pull/119 how to temporary workaround buggy `mysql_enable_utf8` for older DBD::mysql verions (< 4.042).
