### ISSUE TITLE
Error building with latest MySQL 8.0 preview

### ISSUE THREAD

**Issue by gquipster** [perl5-dbi/DBD-mysql#149]
# make
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- mysql.bs blib/arch/auto/DBD/mysql/mysql.bs 644
cc -c  -I/usr/local/lib/perl/5.18.2/auto/DBI -I/usr/include/mysql -DDBD_MYSQL_WITH_SSL -DDBD_MYSQL_INSERT_ID_IS_GOOD -g  -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fstack-protector -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"4.043\" -DXS_VERSION=\"4.043\" -fPIC "-I/usr/lib/perl/5.18/CORE"   dbdimp.c
dbdimp.c: In function ‘mysql_dr_connect’:
dbdimp.c:1749:11: error: unknown type name ‘my_bool’
           my_bool secauth = 0;
           ^
dbdimp.c:1754:31: error: ‘MYSQL_SECURE_AUTH’ undeclared (first use in this function)
           mysql_options(sock, MYSQL_SECURE_AUTH, &secauth);
                               ^
dbdimp.c:1754:31: note: each undeclared identifier is reported only once for each function it appears in
dbdimp.c: In function ‘mysql_st_prepare’:
dbdimp.c:3010:24: warning: assignment from incompatible pointer type [enabled by default]
           bind->is_null=      (char*) &(fbind->is_null);
                        ^
dbdimp.c: In function ‘mysql_st_internal_execute41’:
dbdimp.c:3559:13: error: unknown type name ‘my_bool’
             my_bool on = 1;
             ^
dbdimp.c: In function ‘mysql_describe’:
dbdimp.c:3842:25: error: ‘my_bool’ undeclared (first use in this function)
       buffer->is_null= (my_bool*) &(fbh->is_null);
                         ^
dbdimp.c:3842:33: error: expected expression before ‘)’ token
       buffer->is_null= (my_bool*) &(fbh->is_null);
                                 ^
dbdimp.c:3843:31: error: expected expression before ‘)’ token
       buffer->error= (my_bool*) &(fbh->error);
                               ^
make: *** [dbdimp.o] Error 1

# mysql --version
mysql  Ver 8.0.3-rc for Linux on x86_64 (MySQL Community Server (GPL))

# perl -v

This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
(with 44 registered patches, see perl -V for more detail)

**Comment by pali** [comment]
This issue was fixed in https://github.com/gooddata/DBD-MariaDB repository.

**Comment by mbeijen** [comment]
This issue is fixed since v 4.044.

**Comment by hepcat72** [comment]
So how do you get around this issue on a Mac?
