### ISSUE TITLE
If I updated the Travis CI build to test against MariaDB10.0 would it be accepted?

### ISSUE THREAD

**Issue by ericcurtin** [perl5-dbi/DBD-mysql#150]
May use this module for MariaDB 10.0 integration... Want to be confident that this is still compatible...

**Comment by pali** [comment]
MariaDB 10.0 worked, but was reverted from Travis. Last commit which it includes is there:
https://github.com/perl5-dbi/DBD-mysql/blob/1ece6b4b8630a1cf348373aa41cbe5f748dcd62a/.travis.yml#L85

**Comment by pali** [comment]
It would not work right now. Lot of required changes were reverted, so it either just fail or provide false results. Currently DBD::mysql development is freezed until other people decide how to solve problems... One option is that development would continue in new branch where changes would be reintroduced, so your pull request would be useless (if this option would be chosen). See dbi mailing list for future discussion.

**Comment by ericcurtin** [comment]
I forked anyway. Just to test a build to be 110% sure. Good to know 10.0.x still works:

https://github.com/ericcurtin/DBD-mysql

**Comment by ericcurtin** [comment]
Just wondering, have the other people decided how to solve the MariaDB compatibility problem? Otherwise my team may have to consider moving off this perl module long term in order to retain MariaDB compatibility.

**Comment by pali** [comment]
We have decided to fork it under new name DBD::MariaDB: https://github.com/gooddata/DBD-MariaDB
There is also Travis setup with MariaDB 10.2 and 10.3 versions which seems to work: https://travis-ci.org/gooddata/DBD-MariaDB

**Comment by dveeden** [comment]
The current version has multiple MariaDB versions in the Travis config.
Note that #268 is preventing this work working as intended.
