### ISSUE TITLE
Use options interface for net_buffer_length in MariaDB 10.2.9+

### ISSUE THREAD

**Issue by amaltsev** [perl5-dbi/DBD-mysql#220]
With MariaDB 10.2.9 DBD::mysql gives this diagnostic at start:

```.../DBD/mysql/mysql.so: undefined symbol: net_buffer_length at .../x86_64-linux/DynaLoader.pm line 193.```

The reason is that MariaDB 10.2.9 does not export net_buffer_length any more and the same options interface needs to be used as in MySQL 7.2.9. There is already code for it in the driver, but its condition needs to change to something like this:
```--- mysql.xs.orig	2017-11-18 08:15:03.213385668 -0800
+++ mysql.xs	2017-11-18 08:36:18.330180620 -0800
@@ -790,7 +790,8 @@
     D_imp_dbh(dbh);
     IV type = 0;
     SV* retsv=NULL;
-#if !defined(MARIADB_BASE_VERSION) && MYSQL_VERSION_ID >= 50709
+#if (!defined(MARIADB_BASE_VERSION) && MYSQL_VERSION_ID >= 50709) || \
+    (defined(MARIADB_VERSION_ID) && MARIADB_VERSION_ID >= 100209)
 /* MariaDB 10 is not MySQL source level compatible so this only applies to MySQL*/
     IV buffer_len;
 #endif 
@@ -822,7 +823,8 @@
 	    retsv = newSVpvn("`", 1);
 	    break;
 	case SQL_MAXIMUM_STATEMENT_LENGTH:
-#if !defined(MARIADB_BASE_VERSION) && MYSQL_VERSION_ID >= 50709
+#if (!defined(MARIADB_BASE_VERSION) && MYSQL_VERSION_ID >= 50709) || \
+    (defined(MARIADB_VERSION_ID) && MARIADB_VERSION_ID >= 100209)
         /* MariaDB 10 is not MySQL source level compatible so this
            only applies to MySQL*/
 	    /* mysql_get_option() was added in mysql 5.7.3 */
```

Related to https://github.com/perl5-dbi/DBD-mysql/pull/42

**Comment by renormalist** [comment]
I can confirm this fix as working.

**Comment by pali** [comment]
Above patch is not fully correct. Better version was included in https://github.com/gooddata/DBD-MariaDB repository.

**Comment by greatquux** [comment]
The problem with DBD-MariaDB is that it is not a drop-in replacement for DBD-mysql.

**Comment by Frank071** [comment]
I also confirm the patch, but I do agree that it would be better to start using the option for the first version that supports it (10.2.2). Hoping for a quick release...

**Comment by mbeijen** [comment]
I fixed it with https://github.com/perl5-dbi/DBD-mysql/commit/0f0cebe87fab335873fd3701bc304922da826940 which is now in master.
