### ISSUE TITLE
DBD-MySQL on CentOS force dependence MariaDB 5.5 while is installed MariaDB 10.0

### ISSUE THREAD

**Issue by Seizetsu** [perl5-dbi/DBD-mysql#252]
Hello,
if on CentOS is already installed MariaDB version 10.0 from official MariaDB repo, perl-DBD-MySQL take mariadb5.5-libs as dependence creating a package conflict:

Transaction check error:
file /etc/my.cnf conflicts between attempted installs of mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64 and MariaDB-common-10.0.35-1.el6.x86_64
file /usr/lib64/mysql/plugin/dialog.so conflicts between attempted installs of mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64 and MariaDB-common-10.0.35-1.el6.x86_64
file /usr/lib64/mysql/plugin/mysql_clear_password.so conflicts between attempted installs of mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64 and MariaDB-common-10.0.35-1.el6.x86_64
file /usr/share/mysql/czech/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/danish/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/dutch/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/english/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/estonian/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/french/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/german/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/greek/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/hungarian/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/italian/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/japanese/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/korean/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/norwegian-ny/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/norwegian/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/polish/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/portuguese/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/romanian/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/russian/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/serbian/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/slovak/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/spanish/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/swedish/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
file /usr/share/mysql/ukrainian/errmsg.sys conflicts between attempted installs of MariaDB-server-10.0.35-1.el6.x86_64 and mariadb-libs-2:5.5.52-1.el7.cloudlinux.x86_64
Error Summary

**Comment by pali** [comment]
This looks like CentOS problem, nothing related to version of driver on CPAN or github.

**Comment by dveeden** [comment]
You should not mix MariaDB 10.0 and MariaDB 5.5.
Probably you need to install `MariaDB-compat` which has the compatibility libraries on which `perl-DBD-MySQL` depends.
Another option is to compile DBD::mysql against MariaDB 10.0. You'll need to install `MariaDB-devel` to be able to do that.

This looks like an issue either on your system or in the way DBD::mysql is packaged on your system.
