### ISSUE TITLE
integer values are returned as string

### ISSUE THREAD

**Issue by KES777** [perl5-dbi/DBD-mysql#253]
OpenAPI schema which distinguish `string` and `number` raise validation errors

In our code we do something like:
```
	my $data =  $c->model->xcreate( $raw );
	$c->render( 'country/show',  response => $data );
```

The schema `Country` is defined as:
```
    Country:
      type: object
      properties:
        id:
          type: integer
        code:
          type: string
        default_language_id:
          type: integer
```

at `DBIx/Class/Storage/DBI/mysql.pm:34` the `$dbh->{mysql_insertid}` is:
```
SV = PVLV(0x14009c0) at 0xf32c300
  REFCNT = 1
  FLAGS = (SMG,RMG,POK,pPOK)           <<<<<<<<<<<< the type of value
  IV = 0
  NV = 0
  PV = 0xf3233f0 "29"\0      <<<<<<<< interesting value
  CUR = 2
  LEN = 10
  MAGIC = 0xf318500
    MG_VIRTUAL = &PL_vtbl_packelem
    MG_TYPE = PERL_MAGIC_tiedelem(p)
    MG_FLAGS = 0x06
      REFCOUNTED
      GSKIP
    MG_OBJ = 0xec22e50
    SV = IV(0xec22e40) at 0xec22e50
      REFCNT = 2
      FLAGS = (ROK)
      RV = 0xeb44a70
      SV = PVHV(0xedc0c60) at 0xeb44a70
        REFCNT = 9
        FLAGS = (OBJECT,RMG,OOK,SHAREKEYS)
        MAGIC = 0xed4c250
          MG_VIRTUAL = 0
          MG_TYPE = PERL_MAGIC_ext(~)
          MG_FLAGS = 0x02
            REFCOUNTED
          MG_OBJ = 0xeb44d70
          SV = PVMG(0xeb712d0) at 0xeb44d70
            REFCNT = 1
            FLAGS = (OBJECT)
            IV = 0
            NV = 0
            PV = 0xed4c070 "\227\340\30\0\0\0\0\0\2\0\0\0\0\0\0\0\20M\264\16\0\0\0\0008.\302\16\0\0\0\0\300\20v\16\0\0\0\0\0\0\0\0\0\0\0\0\310\216\323\16\0\0\0\0\210M\264\16\0\0\0\0\4\0\0\0\0\0\0\0\37P\0\0\0\0\0\0\320\364\265\16\0\0\0\0\240M\264\16\0\0\0\0000K\264\16\0\0\0\0\0K\264\16\0\0\0\0\30K\264\16\0\0\0\0\0\0\0\0\0\0\0\0P\0\0\0\0\0\0\0\270M\264\16\0\0\0\0\0\0\0\0\0\0\0\0\220\302\324\16\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"\0
            CUR = 192
            LEN = 194
            STASH = 0xeb41cb8	"DBD::mysql::db_mem"
          MG_PTR = 0xed4c070 ""
        STASH = 0xeb809a8	"DBI::db"
        AUX_FLAGS = 0
        ARRAY = 0xf30f880  (0:5, 1:7, 2:4)
        hash quality = 122.3%
        KEYS = 15
        FILL = 11 (cached = 0)
        MAX = 15
        RITER = -1
        EITER = 0x0
        RAND = 0xd31cd629
        Elt "CachedKids" HASH = 0x851eeaf0
        SV = IV(0xee168a8) at 0xee168b8
          REFCNT = 1
          FLAGS = (ROK)
          RV = 0x34512c0
    MG_LEN = -2
    MG_PTR = 0xf32c138 => HEf_SVKEY
    SV = PV(0xf3025e0) at 0xf32c138
      REFCNT = 2
      FLAGS = (POK,pPOK)
      PV = 0xf2dd420 "mysql_insertid"\0
      CUR = 14
      LEN = 16
  TYPE = T
  TARGOFF = 0
  TARGLEN = 0
  TARG = 0x18fbc98
  FLAGS = 0
```

If data transferring with `MySQL` data base is at binary mode the **driver should not convert integer to string**

**Comment by pali** [comment]
Hi @KES777! Perl at runtime internally adds or remove SvFLAGS at any time and you should not depend on it. In Perl `"29" == 29` and also `"29" eq 29`. If Perl scalar `$a` contains `"29"` and another Perl scalar `$b` contains value `29` then both scalars `$a` and `$b` are same and equivalent. Perl can at any time converts internal `29` to internal `"29"`, but still it represents same value. So you should not depends on SvFLAGS otherwise you may have a future problems with updating cpan modules or upgrading perl itself. About numbers, you can look also into perlnumber documentation: https://perldoc.perl.org/perlnumber.html

> If data transferring with MySQL data base is at binary mode

There is nothing like `binary` mode in MySQL. SQL queries are strings, responses too. But MySQL protocol provides for responses type of column.

**Comment by Grinnz** [comment]
Correct. Schema validation for integer can only validate that the value consists of integral digits, it cannot care about perl's internal representation.

**Comment by pali** [comment]
For checking if scalar has numeric value you should use standard perl function `looks_like_number()`. It is available in the Scalar::Util module, see: https://perldoc.perl.org/Scalar/Util.html#looks_like_number

If it is not enough you can use cpan module Scalar::Util::Numeric, see:
https://metacpan.org/pod/Scalar::Util::Numeric

Or write your own regexes for checking for numbers with your custom restrictions.

**Comment by Grinnz** [comment]
It's important to remember that looks_like_number will only tell if you if Perl would decide to use it as a number (without warning). It will consider the strings 'inf' and 'nan' to be numbers, as well as strings like '5.7e-3'.

Usually for validation you want more specific regexes. Some more examples: https://metacpan.org/pod/Types::Standard https://metacpan.org/pod/Regexp::Common

**Comment by KES777** [comment]
If response from mysql come as string - that is OK.

Thus I should not rely on perl value and coerce it relaying on what is defined at schema.

Because I do not know how client tools will react when it receive `"23"` or `23`

**Comment by pali** [comment]
If you need to know type of column then DBI provides it via `TYPE` attribute, see documentation: https://metacpan.org/pod/DBI#TYPE
