### ISSUE TITLE
token ""mariadb-10.1"" is not valid in preprocessor expressions

### ISSUE THREAD

**Issue by eserte** [perl5-dbi/DBD-mysql#262]
Compiling DBD-mysql-4.047 fails on debian/stretch systems:
```
cc -c  -I/opt/perl-5.24.3/lib/site_perl/5.24.3/x86_64-linux/auto/DBI -I/usr/include/mysql -DDBD_MYSQL_WITH_SSL -g  -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2   -DVERSION=\"4.047\" -DXS_VERSION=\"4.047\" -fPIC "-I/opt/perl-5.24.3/lib/5.24.3/x86_64-linux/CORE"   dbdimp.c
In file included from /usr/include/mysql/mysql.h:76:0,
                 from dbdimp.h:21,
                 from dbdimp.c:15:
dbdimp.c: In function 'mysql_dr_connect':
/usr/include/mysql/mysql_version.h:16:31: error: token ""mariadb-10.1"" is not valid in preprocessor expressions
 #define MARIADB_BASE_VERSION  "mariadb-10.1"
                               ^
dbdimp.c:1910:56: note: in expansion of macro 'MARIADB_BASE_VERSION'
 #if (MYSQL_VERSION_ID >= 50723) && (MYSQL_VERSION_ID < MARIADB_BASE_VERSION)
                                                        ^~~~~~~~~~~~~~~~~~~~
/usr/include/mysql/mysql_version.h:16:31: error: token ""mariadb-10.1"" is not valid in preprocessor expressions
 #define MARIADB_BASE_VERSION  "mariadb-10.1"
                               ^
dbdimp.c:1917:56: note: in expansion of macro 'MARIADB_BASE_VERSION'
 #if (MYSQL_VERSION_ID >= 50600) && (MYSQL_VERSION_ID < MARIADB_BASE_VERSION)
                                                        ^~~~~~~~~~~~~~~~~~~~
dbdimp.c: In function 'mysql_st_prepare':
dbdimp.c:3200:24: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
           bind->is_null=      (_Bool*) &(fbind->is_null);
                        ^
Makefile:355: recipe for target 'dbdimp.o' failed
make: *** [dbdimp.o] Error 1
```
DBD-mysql-4.046 compiled fine on this system.

**Comment by cventers** [comment]
Sample problem with DBD-mysql-4.047 on CentOS 7.

"/opt/rh/rh-perl526/root/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- mysql.bs blib/arch/auto/DBD/mysql/mysql.bs 644
gcc -c  -I/opt/git/perl5lib-el7-x86_64-526/perl5lib/lib/x86_64-linux-thread-multi/auto/DBI -I/usr/include/mysql -DDBD_MYSQL_WITH_SSL -g  -D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g   -DVERSION=\"4.047\" -DXS_VERSION=\"4.047\" -fPIC "-I/opt/rh/rh-perl526/root/usr/lib64/perl5/CORE"   dbdimp.c
In file included from /usr/include/mysql/mysql.h:72:0,
                 from dbdimp.h:21,
                 from dbdimp.c:15:
dbdimp.c: In function ‘mysql_dr_connect’:
/usr/include/mysql/mysql_version.h:16:31: error: token ""mariadb-5.5"" is not valid in preprocessor expressions
 #define MARIADB_BASE_VERSION  "mariadb-5.5"
                               ^
dbdimp.c:1910:56: note: in expansion of macro ‘MARIADB_BASE_VERSION’
 #if (MYSQL_VERSION_ID >= 50723) && (MYSQL_VERSION_ID < MARIADB_BASE_VERSION)
                                                        ^
/usr/include/mysql/mysql_version.h:16:31: error: token ""mariadb-5.5"" is not valid in preprocessor expressions
 #define MARIADB_BASE_VERSION  "mariadb-5.5"
                               ^
dbdimp.c:1917:56: note: in expansion of macro ‘MARIADB_BASE_VERSION’
 #if (MYSQL_VERSION_ID >= 50600) && (MYSQL_VERSION_ID < MARIADB_BASE_VERSION)
                                                        ^
dbdimp.c:1936:19: warning: unused variable ‘ssl_mode’ [-Wunused-variable]
      unsigned int ssl_mode;
                   ^
dbdimp.c: In function ‘mysql_st_prepare’:
dbdimp.c:3200:24: warning: assignment from incompatible pointer type [enabled by default]
           bind->is_null=      (_Bool*) &(fbind->is_null);
                        ^
make: *** [dbdimp.o] Error 1
  CAPTTOFU/DBD-mysql-4.047.tar.gz
  /usr/bin/make -- NOT OK

**Comment by Nuadh** [comment]
fixed in FreeBSD with the following patch (only the 3rd file should be relevant for you): [bugs.freebsd.org](https://bugs.freebsd.org/bugzilla/attachment.cgi?id=196990&action=diff)

**Comment by bramverhelst** [comment]
I also had this issue with a DockerFile (together with #263). Sticking to version 4.046 keeps everything working

**Comment by eserte** [comment]
Same problem with DBD-mysql-4.048, it seems.

**Comment by dveeden** [comment]
https://travis-ci.org/perl5-dbi/DBD-mysql/jobs/419865071 has this:

```
...
Setting environment variables from .travis.yml
$ export DB=MariaDB
$ export VERSION=10.2.1
...
# mysql_clientversion is: 50561
# mysql_serverversion is: 50633
# mysql_hostinfo is: Localhost via UNIX socket
# mysql_serverinfo is: 5.6.33-0ubuntu0.14.04.1
...
```

**Comment by akalinux** [comment]
When will the bug fix be released?

**Comment by graz68a** [comment]
+1

**Comment by dur-randir** [comment]
@CaptTofu what's the point of closing the issue while not making the advertised version (4.049) available to users?

**Comment by todd-richmond** [comment]
Any ETA for 4.049 update on CPAN? We are stuck at 4.046_01 until it is made available

**Comment by dveeden** [comment]
Sorry it took so long, but 4.049 has been uploaded
