### ISSUE TITLE
Support for X-protocol

### ISSUE THREAD

**Issue by CaptTofu** [perl5-dbi/DBD-mysql#266]
Ticket for adding X-protocol support
* libmysql? 
* where handled, and where in the driver to implement?

**Comment by dveeden** [comment]
Looks like "Connector/C++ 8.0 X DevAPI for C" might be what we're looking for:
https://dev.mysql.com/doc/dev/connector-cpp/8.0/xapi_ref.html

**Comment by dveeden** [comment]
As libmysqlclient doesn't support X-Protocol this isn't something for DBD::mysql

DBD::mysqlx was started to use the C API of Connector/C++, which supports X-Protocol but development on that has halted. While X-Protocol has some interesting features there doesn't seem to be a strong demand for it either.
