### ISSUE TITLE
Travis-CI setup broken

### ISSUE THREAD

**Issue by dveeden** [perl5-dbi/DBD-mysql#268]
Related: https://github.com/perl5-dbi/DBD-mysql/issues/262#issuecomment-421616497

Looks like 6fd72e55c9771b25b5775d08a120baae3181806e ("New version 4.043 - the same as 4.041") removed some critical bits of the `.travis-ci.yaml` file causing tests to always run against the system version of MySQL instead of the specified MySQL or MariaDB version.
These were originally introduced in 26fbef8a67bd8c3954d376dfb424261943752209

We should fix the `before_install` etc.

**Comment by dveeden** [comment]
@CaptTofu @mbeijen

**Comment by CaptTofu** [comment]
looking at this.

**Comment by CaptTofu** [comment]
@dveeden do you mean the removal of the `before_install` script code?

**Comment by dveeden** [comment]
@CaptTofu Yes.
The current Travis-CI setup always tests with the same MySQL version and not the test matrix.
So it looks like a new commit is 'safe', but it might not be.
I'm trying in https://github.com/dveeden/DBD-mysql/tree/dvaneeden/travis_fix to merge the current and old config into a new config.
