### ISSUE TITLE
Quoting without a dbh

### ISSUE THREAD

**Issue by dveeden** [perl5-dbi/DBD-mysql#272]
Currently a dbh is needed to get the quoting identifier "`". Would be nice to not need a dbh for that if possible. Also it might be nice to test if the [ANSI_QUOTES](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_ansi_quotes) works correctly.

**Comment by pali** [comment]
Such thing is not possible due to MySQL itself. Based on session settings (e.g. NO_BACKSLASH_ESCAPES and others) `'` is either escaped by `\` or by duplicating `'`.

**Comment by dveeden** [comment]
From [the manual](https://dev.mysql.com/doc/refman/8.0/en/mysql-real-escape-string.html):
"The mysql argument must be a valid, open connection because character escaping depends on the character set in use by the server."

It would be possible to create a function which would accept a context (sql_mode, charset) so it could work w/o a connection. But in that case the function wouldn't be very useful and can easily be implemented elsewhere.

cc @druud

While looking into this I found that the handling of NO_BACKSLASH_ESCAPES on 5.7+ was broken.
See #297

**Comment by pali** [comment]
For DBD::MariaDB we included these changes to fix problems with NO_BACKSLASH_ESCAPES. Special check for SERVER_STATUS_NO_BACKSLASH_ESCAPES is needed too.
https://github.com/gooddata/DBD-MariaDB/pull/77/files
https://github.com/gooddata/DBD-MariaDB/pull/95/files
