### ISSUE TITLE
DBD-mysql wont't install on Mac X Yosemite

### ISSUE THREAD

**Issue by rodrigoreis1** [perl5-dbi/DBD-mysql#289]
Hi there,

I'm having a hard time to install the Perl non-CORE module DBD::mysql. I've tried too many things to list here. My last attempt failed as below:

build.log below

cpanm (App::cpanminus) 1.7044 on perl 5.026002 built for darwin-thread-multi-2level
Work directory is /Users/rodrigoreis/.cpanm/work/1546266298.21521
You have make /usr/bin/make
You have /Users/rodrigoreis/anaconda3/bin/curl
You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
You have /usr/bin/unzip
Searching DBD::mysql () on cpanmetadb ...
--> Working on DBD::mysql
Fetching http://www.cpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-4.049.tar.gz
-> OK
Unpacking DBD-mysql-4.049.tar.gz
Entering DBD-mysql-4.049
Checking configure dependencies from META.json
Checking if you have Data::Dumper 0 ... Yes (2.167)
Checking if you have Devel::CheckLib 1.09 ... Yes (1.13)
Checking if you have DBI 1.609 ... Yes (1.642)
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.24)
Configuring DBD-mysql-4.049
Running Makefile.PL

PLEASE NOTE:

For 'make test' to run properly, you must ensure that the
database user 'rodrigoreis' can connect to your MySQL server
and has the proper privileges that these tests require such
as 'drop table', 'create table', 'drop procedure', 'create procedure'
as well as others.

mysql> grant all privileges on test.* to 'rodrigoreis'@'localhost' identified by 's3kr1t';

You can also optionally set the user to run 'make test' with:

perl Makefile.PL --testuser=username

I will use the following settings for compiling and testing:

  cflags        (mysql_config) = -I/usr/local/opt/mysql-client/include/mysql
  embedded      (guessed     ) = 
  ldflags       (guessed     ) = 
  libs          (mysql_config) = -L/usr/local/opt/mysql-client/lib -lmysqlclient -lssl -lcrypto
  mysql_config  (guessed     ) = mysql_config
  nocatchstderr (default     ) = 0
  nofoundrows   (default     ) = 0
  nossl         (default     ) = 0
  testdb        (default     ) = test
  testhost      (default     ) = 
  testpassword  (default     ) = 
  testport      (default     ) = 
  testsocket    (default     ) = 
  testuser      (guessed     ) = rodrigoreis

To change these settings, see 'perl Makefile.PL --help' and
'perldoc DBD::mysql::INSTALL'.

Checking if libs are available for compiling...
dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/rodrigoreis/.cpanm/work/1546266298.21521/DBD-mysql-4.049/assertlib4_4mCXOu
  Reason: image not found
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/rodrigoreis/.cpanm/work/1546266298.21521/DBD-mysql-4.049/assertlibAbeD4DiS
  Reason: image not found
wrong result: 'ssl', 'crypto'
-> N/A
-> FAIL Configure failed for DBD-mysql-4.049. See /Users/rodrigoreis/.cpanm/work/1546266298.21521/build.log for details.
___________________________________________________________
I tried:

brew install --upgrade openssl
brew unlink openssl && brew link openssl --force

Didn't make any difference.

My system is: 
OS X Yosemite 10.10.5
Perl 5.26.2
mysql  Ver 14.14 Distrib 5.7.23, for osx10.10 (x86_64)
gcc 
xcode-select version 2339

**Comment by worthmine** [comment]
see #161 I could install it to MacOS X Mojave

**Comment by dveeden** [comment]
Closing this and following up in #161
