### ISSUE TITLE
install DBD-mysql to macOS 10.13.x High Sierra 

### ISSUE THREAD

**Issue by jainraje** [perl5-dbi/DBD-mysql#298]
Anyone had success install into macOS 10.13.x High Sierra?

I've tried using home-brew, cpan but always various errors. I'm now manually installing and getting an error during the final link:

$>DBD-mysql-4.050$ make
Skip blib/lib/DBD/mysql/INSTALL.pod (unchanged)
Skip blib/lib/DBD/mysql.pm (unchanged)
Skip blib/lib/Bundle/DBD/mysql.pm (unchanged)
Skip blib/lib/DBD/mysql/GetInfo.pm (unchanged)
Running Mkbootstrap for mysql ()
chmod 644 "mysql.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- mysql.bs blib/arch/auto/DBD/mysql/mysql.bs 644
cc -c  -I/System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/auto/DBI -I/usr/local/mysql/include -DDBD_MYSQL_WITH_SSL -g  -arch x86_64 -arch i386 -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os   -DVERSION=\"4.050\" -DXS_VERSION=\"4.050\"  "-I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"   dbdimp.c
cc -c  -I/System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/auto/DBI -I/usr/local/mysql/include -DDBD_MYSQL_WITH_SSL -g  -arch x86_64 -arch i386 -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os   -DVERSION=\"4.050\" -DXS_VERSION=\"4.050\"  "-I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"   mysql.c
cc -c  -I/System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/auto/DBI -I/usr/local/mysql/include -DDBD_MYSQL_WITH_SSL -g  -arch x86_64 -arch i386 -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os   -DVERSION=\"4.050\" -DXS_VERSION=\"4.050\"  "-I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"   socket.c
rm -f blib/arch/auto/DBD/mysql/mysql.bundle
LD_RUN_PATH="/usr/local/mysql/lib" cc  -arch x86_64 -arch i386 -bundle -undefined dynamic_lookup -fstack-protector  dbdimp.o mysql.o socket.o  -o blib/arch/auto/DBD/mysql/mysql.bundle  \
	   -L/usr/local/mysql/lib -lmysqlclient -lssl -lcrypto   \
	  
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /usr/local/mysql/lib/libmysqlclient.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/mysql/lib/libmysqlclient.dylibld: warning: 
ignoring file /usr/local/mysql/lib/libssl.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/mysql/lib/libssl.dylib
ld: warning: ignoring file /usr/local/mysql/lib/libcrypto.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/mysql/lib/libcrypto.dylib
chmod 755 blib/arch/auto/DBD/mysql/mysql.bundle
Manifying 3 pod documents

My high sierra was upgraded from a older OS version so my thinking is the i386 flag is left over from the prior install.

How can the -arch i386 flag be removed?

Any help or guidance will be appreciated.

TIA

**Comment by dveeden** [comment]
Combining this with #161

**Comment by krisgale** [comment]
> I've tried using home-brew, cpan but always various errors. I'm now manually installing and getting an error during the final link:

this may help you:
https://github.com/perl5-dbi/DBD-mysql/issues/161#issuecomment-614399171
