### ISSUE TITLE
DBD-mysql 4.50 configure failed

### ISSUE THREAD

**Issue by code-share1** [perl5-dbi/DBD-mysql#311]
I'm building the DBD-mysql 4.50 in cross compile env, but encounters below configure error:

| I will use the following settings for compiling and testing:
| 
|   cflags        (mysql_config) = -I/yocto/builds/upgrade1/tmp/work/core2-64-poky-linux/DBD-mysql/4.050-r0/recipe-sysroot/usr/include/mysql -I/yocto/builds/upgrade1/tmp/work/core2-64-poky-linux/DBD-mysql/4.050-r0/recipe-sysroot/usr/include/mysql/..
|   embedded      (mysql_config) =
|   ldflags       (guessed     ) =
|   libs          (mysql_config) = -L/yocto/builds/upgrade1/tmp/work/core2-64-poky-linux/DBD-mysql/4.050-r0/recipe-sysroot/usr/lib -lmariadb -lz -ldl -lm -lssl -lcrypto
|   mysql_config  (guessed     ) = mysql_config
|   nocatchstderr (default     ) = 0
|   nofoundrows   (default     ) = 0
|   nossl         (default     ) = 0
|   testdb        (default     ) = test
|   testhost      (default     ) =
|   testpassword  (default     ) =
|   testport      (default     ) =
|   testsocket    (default     ) =
|   testuser      (guessed     ) = root
| 
| To change these settings, see 'perl Makefile.PL --help' and
| 'perldoc DBD::mysql::INSTALL'.
| 
| Checking if libs are available for compiling...
| wrong result: 'mariadb', 'z', 'dl', 'm', 'ssl', 'crypto'
| WARNING: /yocto/builds/upgrade1/tmp/work/core2-64-poky-linux/DBD-mysql/4.050-r0/temp/run.do_configure.33810:1 exit 2 from 'perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1 PERL=$(which perl)'

BTW, # ls /yocto/builds/upgrade1/tmp/work/core2-64-poky-linux/DBD-mysql/4.050-r0/recipe-sysroot/usr/lib/libmariadb.so
/yocto/builds/upgrade1/tmp/work/core2-64-poky-linux/DBD-mysql/4.050-r0/recipe-sysroot/usr/lib/libmariadb.so

The checked libs actually exist under /yocto/builds/upgrade1/tmp/work/core2-64-poky-linux/DBD-mysql/4.050-r0/recipe-sysroot/usr/lib, why still occurs the error? Any suggestions?

**Comment by dveeden** [comment]
Compiling with MariaDB client libraries is no longer supported in master. Please try again with MySQL client libraries.
