### ISSUE TITLE
BIGINT type error conversion with amavisd-new

### ISSUE THREAD

**Issue by tomsommer** [perl5-dbi/DBD-mysql#312]
#78 is still not fixed.

It still does not work with DBD-MySQL 4.050, Perl 5.16.3 and amavisd-new-2.11.1 (20181009) - foreign key constraint fails because of BIGINT type-error.

Rolling back to 4.037 does work, so it is due to a change in DBD-MySQL

**Comment by pali** [comment]
Hi @tomsommer! Are you able to test if `DBD::MariaDB` driver (http://metacpan.org/pod/DBD::MariaDB) is working with amavisd-new? In `DBD::MariaDB` I tried to fix all known bug found in DBD::mysql.

**Comment by tomsommer** [comment]
I am not able to test this right now, but the problem might be isolated to amavis-new, and thus might better be fixed there. I will look into this angle.
