### ISSUE TITLE
Test 05dbcreate.t is failing when executed on non-default socket

### ISSUE THREAD

**Issue by vlmarek** [perl5-dbi/DBD-mysql#323]
Hello,

we execute tests over non-default socket to avoid collision with other tests which might be running. The test wipes out database name from connect string before running, but it also wipes out the socket. I'm attaching the patch we use to correct this issue.

Thank you
__ 
  Vlad

**Comment by vlmarek** [comment]
[05_test.txt](https://github.com/perl5-dbi/DBD-mysql/files/5541989/05_test.txt)

**Comment by dveeden** [comment]
Could you send this as a pull request?

**Comment by vlmarek** [comment]
Hello, sure, thank you for looking into this.

**Comment by dveeden** [comment]
I've configured MySQL like this:
```ini
[mysqld]
socket=/var/lib/mysql/mysql_foobar.sock
port=3307
```

And `make test` results in a `Result: PASS`. So either I failed to reproduce the issue or the patch isn't needed anymore.

However I the `--testsocket` option was missing in a few places. So let's fix that as well.
