### ISSUE TITLE
DBI error messages not using UTF 8 

### ISSUE THREAD

**Issue by arnold-b** [perl5-dbi/DBD-mysql#328]
Hello, 

i set Mysql DBI to UTF8. Everything works fine till i get a db error. 

 my $dbh = DBI->connect($dsn, $userid, $password, { RaiseError => 0,PrintError => 1, mysql_enable_utf8 => 1})

sub dberror{
   my $self = shift;
   my $cmdstr = shift;
   my $sqlerr = $self->{'db'}->errstr;

   print $self->{'cgi'}->header( 'application/json;charset=utf-8' );
   print '{"Result":"false","Mode":"'.$cmdstr.'","DBerr":"'.$sqlerr.'"}';
   $self->print('{"Result":"false","Mode":"'.$cmdstr.'","DBerr":"'.$sqlerr.'"}');

   die "DB Error in $cmdstr : $self->{'db'}->errstr";
}

$sqlstr = 'update contact SET  name="吕飞来", addrtype="s", address="", contactid="265", phonenr="", comment="吕飞来", countryid="CN"'

 my $stmt = $self->{'db'}->prepare($sqlstr) or  $self->dberror("prepare",$sqlstr);
   my $res = $stmt->execute() or $self->dberror("execute",$sqlstr);

Result from error:
{"Result":"false","Mode":"execute","DBerr":"Duplicate entry 'å��é£�æ�¥' for key 'suppname'"} 

no UTF8 for the field value

normal select or update works. only problem, if i get an error

Thanks

**Comment by pali** [comment]
Hello! DBD::mysql perl driver has issues with UTF-8 which cannot be fixed due to backward compatibility with existing applications. If you need fully working UNICODE support you should look at the https://metacpan.org/pod/DBD::MariaDB driver which supports both MySQL and MariaDB servers.

**Comment by arnold-b** [comment]
thanks, i will try
