### ISSUE TITLE
Specifying mysql_enable_utf8mb4=1 doesn't always work depending on where it is specified in DSN

### ISSUE THREAD

**Issue by cmanley** [perl5-dbi/DBD-mysql#360]
For terminology see: https://metacpan.org/pod/DBI#parse_dsn

If I pass mysql_enable_utf8mb4=>1 in the attribute part of a dsn, then it works. Example:
`dbi:mysql(mysql_enable_utf8mb4=>1):database=test;host=localhost`

However, if I pass mysql_enable_utf8mb4=1 in the driver_dsn part of the dsn, then it doesn't have an effect. Example:
`dbi:mysql:database=test;host=localhost;mysql_enable_utf8mb4=1`

To test it, I select a ü character using SQL
`SELECT CHAR(0xC3BC USING utf8mb4), LENGTH(CHAR(0xC3BC USING utf8mb4)), CHAR_LENGTH(CHAR(0xC3BC USING utf8mb4))`

My terminal uses UTF-8 encoding, so I tell the Perl script which encoding to use for STDOUT:
```
-t(STDOUT) && binmode(STDOUT, ':utf8');
-t(STDERR) && binmode(STDERR, ':utf8')
```

then....
```
...
use Encode ();
my $dbh = ....;
my ($char, $byte_length, $char_length) = $dbh->selectrow_array($sql);
print 'character: ' . $char . "\n";
print 'is_utf8?: ' . int(Encode::is_utf8($char)) . "\n";
print 'mysql byte length: ' . $byte_length . "\n";
print 'mysql char length: ' . $char_length . "\n";
print 'perl byte length: ' . bytes::length($char) . "\n";
print 'perl char length: ' . length($char) . "\n";
```

This is what I expect to see and what I get with the first dsn:
```
character: ü
is_utf8?: 1
mysql byte length: 2
mysql char length: 1
perl byte length: 2
perl char length: 1
```
But this is what I get with the second dsn:
```
character: Ã¼ (wrong!)
is_utf8?: 0 (wrong!)
mysql byte length: 2
mysql char length: 1
perl byte length: 2
perl char length: 2 (wrong!)
```

**Comment by dveeden** [comment]
```
#!/bin/perl
use strict;
use v5.36;
use DBI;

my @dsns = (
	"DBI:mysql:database=test;host=localhost;mysql_enable_utf8mb4=1",
	"DBI:mysql(mysql_enable_utf8mb4=1):database=test;host=localhost"
);

for my $dsn (@dsns) {
	say "dsn: " . $dsn;
	my $dbh = DBI->connect($dsn, "xxxxx", "xxxxxxx");

	say "mysql_enable_utf8mb4:" . $dbh->{mysql_enable_utf8mb4};
	
	print $dbh->selectrow_array("SELECT VERSION()") . "\n";
	$dbh->disconnect();
}
```

Output:
```
dsn: DBI:mysql:database=test;host=localhost;mysql_enable_utf8mb4=1
mysql_enable_utf8mb4:0
8.1.0
dsn: DBI:mysql(mysql_enable_utf8mb4=1):database=test;host=localhost
mysql_enable_utf8mb4:1
8.1.0
```

This is with DBD::mysql v5.001

**Comment by dveeden** [comment]
Looks like it is calling `mysql_options()` either when the `mysql_enable_utf8mb4=1` is in the regular DSN or driver DSN. However it isn't registering it correctly internally (`imp_dbh->enable_utf8mb4`).

**Comment by cmanley** [comment]
Thanks!
