### ISSUE TITLE
Another test failure with 5.001

### ISSUE THREAD

**Issue by DrHyde** [perl5-dbi/DBD-mysql#367]
Not sure where `have_transactions` went, as it doesn't seem to have been present in the tests for 4.050 either.

```
# Database 'test' accessible
t/05dbcreate.t .......................... ok

...

t/50chopblanks.t ........................ ok
Undefined subroutine &main::have_transactions called at t/50commit.t line 44.
t/50commit.t ............................
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
```

**Comment by dveeden** [comment]
I don't get the same output:
```
t/50chopblanks.t ........................ ok     
t/50commit.t ............................ ok   
```

This is with master @ ea4fff83d5e473b83993c1c52938bd3d088e0893 and MySQL v8.1.0 and Perl v5.36.1

`have_transactions` is defined here: https://github.com/perl5-dbi/DBD-mysql/blob/ea4fff83d5e473b83993c1c52938bd3d088e0893/t/mysql.dbtest#L37

**Comment by dveeden** [comment]
The `have_transactions` function checks for `have_bdb`, `have_innodb` and `have_gemini`. Only InnoDB is left of these and now is guaranteed to be in pretty much all supported MySQL versions. This means we can remove the storage engine check. 

As this check doesn't check for MyRocks or TokuDB it also isn't working correctly.


A better way to check for storage engines that support transactions is this:
```
sql> SELECT ENGINE, TRANSACTIONS FROM information_schema.ENGINES;
+--------------------+--------------+
| ENGINE             | TRANSACTIONS |
+--------------------+--------------+
| ndbcluster         | NULL         |
| MEMORY             | NO           |
| InnoDB             | YES          |
| PERFORMANCE_SCHEMA | NO           |
| MyISAM             | NO           |
| FEDERATED          | NULL         |
| ndbinfo            | NULL         |
| MRG_MYISAM         | NO           |
| BLACKHOLE          | NO           |
| CSV                | NO           |
| ARCHIVE            | NO           |
+--------------------+--------------+
11 rows in set (0.0004 sec)
```

@DrHyde can you check #368 and let me know what you think?

I would also be interested to know what would be needed to reproduce the issue.
