### ISSUE TITLE
Test for 5.001 fails on version.t

### ISSUE THREAD

**Issue by nakib103** [perl5-dbi/DBD-mysql#370]
Hello!

DBD::mysql recently published the 5.001 version but the `version.t` test in that tag still checking for a version that start with `4.` - 

https://github.com/perl5-dbi/DBD-mysql/blob/fa6280632679b7ed0e087db6a33bd979c27be30a/t/version.t#L9

Because of that the test is failing. Is that a bug?

**Comment by fheyer** [comment]
I experienced this test failure as well building with Perlbrew Perl 5.30.3 on Ubuntu 20.04.6.

**Comment by SteveClement** [comment]
Good to see there is a fix :)
