### ISSUE TITLE
Use of deprecated parts of the MySQL C API

### ISSUE THREAD

**Issue by dveeden** [perl5-dbi/DBD-mysql#375]
https://dev.mysql.com/doc/relnotes/mysql/8.2/en/news-8-2-0.html#mysqld-8-2-0-capi

- `mysql_ssl_set()` - #373 
- `mysql_stmt_bind_param()`

**Comment by dveeden** [comment]
This is not fully possible right now due to this bug: https://bugs.mysql.com/bug.php?id=112893

**Comment by chenrui333** [comment]
@dveeden is this change in 5.004 rather than 5.005?

relates to:
- #169714
- #169715
- #169716

**Comment by chenrui333** [comment]
> In 5.005:
> 
> * [21e9ef2](https://github.com/perl5-dbi/DBD-mysql/commit/21e9ef2cd0d8439944003d32bcbd592ccb8326d7) for `mysql_stmt_bind_param()`

I was mostly curious about that commit, as it did not show the tag as the other two, but thanks for confirming it. Appreciate it.
