### ISSUE TITLE
MYSQL_OPT_COMPRESSION_ALGORITHMS is only supported by mysql 8.0.22 an higher

### ISSUE THREAD

**Issue by thockar** [perl5-dbi/DBD-mysql#376]
the dependency to MySQL 8.0 is broken in 5.0.2, because 'MYSQL_OPT_COMPRESSION_ALGORITHMS' was added in mysql 8.0.22 - so lower versions of clientlibraries will cause DBD::myql compilation to fail

so either change the doc and the Makefile.PL to check for higher 8.0.x versions OR make the use of 'MYSQL_OPT_COMPRESSION_ALGORITHMS' depending on the client library version

**Comment by dveeden** [comment]
https://dev.mysql.com/doc/c-api/8.0/en/mysql-options.html has this: 
![image](https://github.com/perl5-dbi/DBD-mysql/assets/1272980/fc46c748-5570-4edc-90bf-004678038296)

So looks like this was added in 8.0.18 instead.

**Comment by dveeden** [comment]
This was introduced in https://github.com/perl5-dbi/DBD-mysql/pull/372

**Comment by dveeden** [comment]
I would recommend to use the latest minor version of 8.0 to ensure you have all security fixes from MySQL.

@thockar any specific reason to use an older version? What OS do you use?

**Comment by dveeden** [comment]
Thanks for the info. Could you see if https://github.com/perl5-dbi/DBD-mysql/pull/377 fixes this for you?

**Comment by thockar** [comment]
Yes, this fixes the issue (I already tried it similar). Thank you.

#if MYSQL_VERSION_ID >= 80018

This will lead in to the same hard to maintain code for the 5.xxx version - like the 4.xxx code before.
IMO depending on available symbols is more clear - but it's your code !
