### ISSUE TITLE
'cpanm DBD::mysql' fails in perl:5.38 docker image

### ISSUE THREAD

**Issue by ktown007** [perl5-dbi/DBD-mysql#387]
### DBD::mysql version

http://www.cpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-5.002.tar.gz

### MySQL client version

mysql_config --version: 10.11.4 

### Server version

debian

### Operating system version

docker image perl:5.38

### What happened?

DBD::mysql requires MySQL 8.x for building. Version reported by mysql_config --version: 10.11.4 at Makefile.PL

### Other information

cat /root/.cpanm/work/1699052908.7072/build.log
cpanm (App::cpanminus) 1.7047 on perl 5.038000 built for x86_64-linux-gnu
Work directory is /root/.cpanm/work/1699052908.7072
You have make /usr/bin/make
You have /usr/bin/wget
You have /usr/bin/tar: tar (GNU tar) 1.34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching DBD::mysql () on cpanmetadb ...
--> Working on DBD::mysql
Fetching http://www.cpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-5.002.tar.gz
-> OK
Unpacking DBD-mysql-5.002.tar.gz
Entering DBD-mysql-5.002
Checking configure dependencies from META.json
Checking if you have DBI 1.609 ... Yes (1.643)
Checking if you have Devel::CheckLib 1.09 ... Yes (1.16)
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.70)
Checking if you have Data::Dumper 0 ... Yes (2.188)
Configuring DBD-mysql-5.002
Running Makefile.PL

PLEASE NOTE:

For 'make test' to run properly, you must ensure that the
database user '' can connect to your MySQL server
and has the proper privileges that these tests require such
as 'drop table', 'create table', 'drop procedure', 'create procedure'
as well as others.

mysql> CREATE USER ''@'localhost' IDENTIFIED BY 's3kr1t';
mysql> GRANT ALL PRIVILEGES ON test.* TO ''@'localhost';

You can also optionally set the user to run 'make test' with:

perl Makefile.PL --testuser=username

DBD::mysql requires MySQL 8.x for building. Version reported by mysql_config --version: 10.11.4 at Makefile.PL line 450, <PIPE> line 3.
-> N/A
-> FAIL Configure failed for DBD-mysql-5.002. See /root/.cpanm/work/1699052908.7072/build.log for details.

**Comment by dveeden** [comment]
`mysql_config --version: 10.11.4` ← That's not MySQL, that's MariaDB. DBD::mysql needs MySQL as the message indicates.

You can use the [MySQL APT Repository](https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/) for Debian bookworm or install [libmysqlclient-dev](https://packages.debian.org/search?keywords=libmysqlclient-dev) in Debian sid.

**Comment by ktown007** [comment]
aah, I had installed `default-libmysqlclient-dev`. To help the next guy Dockerfile:

  FROM perl:5.38
  RUN apt-get update
  RUN apt-get install -y lsb-release debconf-utils cpanminus
  RUN wget https://dev.mysql.com/get/mysql-apt-config_0.8.28-1_all.deb
  RUN DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.28-1_all.deb
  RUN apt-get update
  RUN apt-get install -y libmysqlclient-dev
  RUN cpanm DBD::mysql

**Comment by dveeden** [comment]
@ktown007 I used your example in #389 but with `RUN wget ...` replaced by `ADD ...`.
