### ISSUE TITLE
Compile fails with MySQL 8.3.0 due to MySQL removing a deprecated function DBD::mysql uses

### ISSUE THREAD

**Issue by tzs** [perl5-dbi/DBD-mysql#411]
### DBD::mysql version

DBD-mysql-5.003

### MySQL client version

8.3.0

### Operating system version

MacOS Sonoma 14.2.1

### What happened?

Build fails with this error:

`dbdimp.c:2796:14: error: call to undeclared function 'mysql_list_fields'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]`
   ` *result= mysql_list_fields(svsock, table, NULL);`
            `.         ^`
It looks like mysql_list_fields [was removed in MySQL 8.3.0](https://github.com/mysql/mysql-server/commit/15d9b4d0e6f0a098165fb595538a9182db604778), which was released 3 weeks ago.

**Comment by DrHyde** [comment]
After comparing the relevant bit of code to that in DBD::MariaDB, I wonder if the call to `mysql_list_fields` (and its surroundings) can just be got rid of. It seems to be in some error checking that is then repeated a few moments later when the query is executed using `mysql_send_query` or `mysql_real_query`.

**Comment by DrHyde** [comment]
For those using Mac OS and homebrew to manage their mysql, I recommend `pin`ning your mysql.

But if you're too late and it's only after a `brew upgrade` broke things that you ended up looking at this issue, then you can `brew tap DrHyde/homebrew-DrHyde` and `brew install mysql-82` to temporarily downgrade.

**Comment by dveeden** [comment]
Looks like `mysql_reload()` now also starts to cause issues: https://github.com/perl5-dbi/DBD-mysql/pull/414#issuecomment-1990935800
