### ISSUE TITLE
Support for MySQL > 8.x / MariaDB

### ISSUE THREAD

**Issue by AndreC10002** [perl5-dbi/DBD-mysql#423]
### What enhancement would you like in DBD::mysql?

Versions newer than 4.052 don't support MySQL newer than 8.x and MariaDB version 10.x.x, (others?).  That causes a big headache and forces a freeze on version 4.052.
I'd like to help with this issue if possible. I run Perl with DBD-MySQL and MariaDB in lots of servers and freezing a module version is a problem.
Thank you very much for maintaining this essential Perl module. Please let me know how I can help with this issue.

### Other information

DBD::mysql requires MySQL 8.x for building. Version reported by mysql_config --version: 10.5.15 at Makefile.PL line 451, <PIPE> line 3.

**Comment by dveeden** [comment]
Hi @AndreC10002 

To make DBD::mysql more maintainable I had to make a few choices. MariaDB and MySQL have diverted more and more and this adds more complexity.

- DBD::mysql now requires MySQL 8.x to build. This should work with any recent 8.0 or 8.3 version. I'll make sure to test with 8.4 once it is released. I have already removed the use of deprecated functions.
- DBD::mysql no longer builds against MySQL 4.x or MySQL 5.x. These are all EOL and this makes things easier to test and maintain.
- DBD::mysql no longer builds against MariaDB. This also removes complexity.

Note that DBD::mysql build against MySQL 8.x can be used to connect to a server running MySQL 5.7, MariaDB, etc.

There is DBD::MariaDB in case you really need to build against MariaDB. The other option is to pin against DBD::mysql v4.x

**Comment by dveeden** [comment]
And as there is no MySQL 9.x or anything that's >8.x I don't think there is a problem with that?

**Comment by Grinnz** [comment]
Please note: https://blogs.perl.org/users/grinnz/2023/12/migrating-from-dbdmysql-to-dbdmariadb.html

**Comment by AndreC10002** [comment]
Thank you for the reference.
