### ISSUE TITLE
Build is broken with gcc14

### ISSUE THREAD

**Issue by MarkusVolk** [perl5-dbi/DBD-mysql#430]
### DBD::mysql version

5.006

### Operating system version

openembedded

### What happened?

| dbdimp.c: In function 'mysql_st_prepare':
| dbdimp.c:3207:24: error: assignment to 'my_bool *' {aka 'char *'} from incompatible pointer type '_Bool *' [-Wincompatible-pointer-types]
|  3207 |           bind->is_null=      (_Bool*) &(fbind->is_null);
|       |  

### Other information

gcc14 changed incompatible-pointer-types from warning to error. Thus build fails.
Adding -Wno-incompatible-pointertypes to CFLAGS works as a workaround

**Comment by dveeden** [comment]
What version of MySQL are you using?

**Comment by MarkusVolk** [comment]
> What version of MySQL are you using?

I'm building with mariadb-10.11.7

**Comment by dveeden** [comment]
Building DBD::mysql requires MySQL 8.x. Building with MariaDB is not supported. Note that DBD:: mysql build against MySQL can connect to MariaDB. If you must use MariaDB either use a v4 version of DBD::mysql or use DBD:: MariaDB.

**Comment by MarkusVolk** [comment]
> Building DBD::mysql requires MySQL 8.x. Building with MariaDB is not supported. Note that DBD:: mysql build against MySQL can connect to MariaDB. If you must use MariaDB either use a v4 version of DBD::mysql or use DBD:: MariaDB.

Ok, thanks for the info. Maybe providing mysql will be the way to go.
