### ISSUE TITLE
5.002: new file installed? 🤔 

### ISSUE THREAD

**Issue by kloczek** [perl5-dbi/DBD-mysql#433]
### DBD::mysql version

5.002

### MySQL client version

N/A

### Server version

N/A

### Operating system version

Linux x86/64

### What happened?

On update my rpm package to 5.002 I found new installed file
```console
RPM build warnings:
    Downloading https://cpan.metacpan.org/modules/by-module/DBD/DBD-mysql-5.002.tar.gz to /home/tkloczko/rpmbuild/SOURCES/DBD-mysql-5.002.tar.gz
    source_date_epoch_from_changelog set but %changelog is missing

RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib64/perl5/vendor_perl/Bundle/DBD/mysql.pm
```
Is it intentional? 🤔

**Comment by dveeden** [comment]
The mentioned file was removed in 2bf2ebd4b2d31320d94d6cbb34063e42cda0df38 in 5.004

It looks like you're building an RPM where the spec file isn't packaging this file. For 5.002 the spec file probably should package this file. I think this is an issue with the spec file and not with DBD::mysql

Upgrading to the latest version will probably fix this. But that also depends on the content of the spec file you're using.
